services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: RANDOM_SECRET # Replace with a secure random string
      USER_SECRET: RANDOM_SECRET # Replace with a secure random string
      LOGIN_USERNAME: username # Replace with a username
      LOGIN_PASSWORD: mypassword # Replace with a custom password
      DATABASE_URL: "file:/data/portnote.db"
    volumes:
      - portnote_data:/data

  agent:
    build:
      context: ./agent
    user: "0:0"
    environment:
      DATABASE_URL: "file:/data/portnote.db"
    volumes:
      - portnote_data:/data

volumes:
  portnote_data:
